content = ''
content += '"use client"\n'
content += 'import { useState } from "react"\n\n'
content += 'export default function Home() {\n'
content += '  const [text, setText] = useState("")\n'
content += '  const [result, setResult] = useState(null)\n'
content += '  const [loading, setLoading] = useState(false)\n\n'
content += '  const analyze = async () => {\n'
content += '    if (!text.trim()) return\n'
content += '    setLoading(true)\n'
content += '    setResult(null)\n'
content += '    try {\n'
content += '      const res = await fetch("http://127.0.0.1:8000/predict", {\n'
content += '        method: "POST",\n'
content += '        headers: { "Content-Type": "application/json" },\n'
content += '        body: JSON.stringify({ text })\n'
content += '      })\n'
content += '      const data = await res.json()\n'
content += '      setResult(data)\n'
content += '    } catch (e) {\n'
content += '      alert("API not running")\n'
content += '    }\n'
content += '    setLoading(false)\n'
content += '  }\n\n'
content += '  return (\n'
content += '    <main className="min-h-screen bg-gray-950 text-white p-8">\n'
content += '      <div className="max-w-2xl mx-auto">\n'
content += '        <h1 className="text-3xl font-bold mb-2 text-purple-400">Fake Job Detector</h1>\n'
content += '        <p className="text-gray-400 mb-6">Paste a job description to check if it is fraudulent.</p>\n'
content += '        <textarea\n'
content += '          className="w-full h-48 bg-gray-800 text-white rounded-lg p-4 mb-4 border border-gray-700"\n'
content += '          placeholder="Paste job description here..."\n'
content += '          value={text}\n'
content += '          onChange={e => setText(e.target.value)}\n'
content += '        />\n'
content += '        <button onClick={analyze} disabled={loading} className="w-full bg-purple-600 text-white font-bold py-3 rounded-lg">\n'
content += '          {loading ? "Analyzing..." : "Analyze Job Posting"}\n'
content += '        </button>\n'
content += '        {result && (\n'
content += '          <div className="mt-8 bg-gray-800 rounded-lg p-6 border border-gray-700">\n'
content += '            <p className="text-2xl font-bold mb-2">{result.prediction === "FAKE" ? "FAKE" : "REAL"}</p>\n'
content += '            <p className="mb-4">Risk: {result.risk_level} | Confidence: {result.confidence}%</p>\n'
content += '            {result.flags.length > 0 && (\n'
content += '              <ul>\n'
content += '                {result.flags.map((flag, i) => (\n'
content += '                  <li key={i} className="text-red-300">🚩 {flag}</li>\n'
content += '                ))}\n'
content += '              </ul>\n'
content += '            )}\n'
content += '          </div>\n'
content += '        )}\n'
content += '      </div>\n'
content += '    </main>\n'
content += '  )\n'
content += '}\n'
with open(r'C:\fake-job-frontend\app\page.js', 'w', encoding='utf-8') as f:
    f.write(content)
print('Done')